language: python
dist: bionic

stages:
  - test
  - deploy

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

script:
  - python pypack.py pypack.py

jobs:
  include:
    - stage: deploy
      if: tag IS present
      python: 2.7
      env:
        - TWINE_USERNAME: "__token__"
        # TWINE_PASSWORD
        - secure: "uNe0+pQy5BIbB6ytbpo+VWztkud487k94mM/zOFWKeRFWTJj/lFWe4BNJYnaRDQiNotiu4yluPNNGXFLc3yoLw0vz9dMfqsN8cyOe3nihtK/c3R5MDLXuJltZZkKBRFNjILE5E6Iwn77aTWcBTigrwQ+GjnVREuPj29lLzSx5SPtTY66Las/E4VxJP3RmIDMBlZQNH+/AD3nEycYk1/b1pBSWeuSUjNIgkmKGPq62YsQSL8JUbAmAEhQUhcz3AxRtvFYX/QwqGaWr9U8KBybNTW1VfmnYVYGCEehfhT07eSdf+K3LiyhksWyM1H2eReYZLRLsqUjvscwZB9qX1+MoXXst8rnOujTLn3aAKFHi/z0dxkoik1jFHE4EmNFRONQj7DrdVg9Rhl+42DZwV4eTmZz1gF7k9Rnz3XMPXqbejlr4ToHigeEezenV5siF6OBgmv3bdkq34mGzqkk1NWQRWv4R/kHnWsoO8wAABVu9UDMy5emQzUVavUhYP6osQ4aUCZB1MEEABNUJtyCg2Q+TOJHfiddlnOVeUOle8+Z26XNvDRh0IuEomXt1cRm7bsGQf0sJHnM9ZUhPp0nTKsHW14TB7EAFt7OZIWzz5SzvdlayVs19txZX9beUSRGlKfYLOgu2cX9/CVXndIvKvUTb4Au+una67A6CSbN803kQE0="

      install:
        - pip install twine
      script:
        - python pypack.py pypack.py
        - twine upload *.zip
